//  Settings.m
//  Monster
//

#import "MSettings.h"

int TILEXSIZE;
int TILEYSIZE;
int MAPXSIZE;
int MAPYSIZE;
float FINGERSCROLLMULTIPLYER;
int MINSCROLLSPEED;
int MAXSCROLLSPEED;
int SELECTIONPIXELPRECISION;
int MAXPROJECTILES;
@implementation MSettings

+(void)load
{
	TILEXSIZE = 64;
	TILEYSIZE = 64;
	MAPXSIZE = 12;
	MAPYSIZE = 12;
	FINGERSCROLLMULTIPLYER = 1.5;
	MINSCROLLSPEED = 1;
	MAXSCROLLSPEED = 25;
	SELECTIONPIXELPRECISION = 32;
	MAXPROJECTILES = 4;
}

@end
